services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\Submissions\:
    # important: do not include FormType, which is optionally injected in SubmissionsPass
    resource: '../src/{Config,Controller,DataContainer,EventListener,Manager,Model,Util}/*'
